name: Trigger auto deployment for container-app-ewwyl33negcou

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-ewwyl33negcou-AutoDeployTrigger-3b21e4dd-470c-4dfc-a154-62e588927d83.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPEWWYL33NEGCOU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPEWWYL33NEGCOU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPEWWYL33NEGCOU_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryewwyl33negcou.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPEWWYL33NEGCOU_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPEWWYL33NEGCOU_REGISTRY_PASSWORD }}
          containerAppName: container-app-ewwyl33negcou
          resourceGroup: expresssample95508feb
          imageToBuild: containerregistryewwyl33negcou.azurecr.io/container-app-ewwyl33negcou:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


